version: '3.8'
services:
  postgres:
    container_name: test_postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: hoge
      POSTGRES_USER: hoge
      POSTGRES_PASSWORD: hoge
    ports:
      - '5432:5432'